name: Build Windows EXE

on:
  push:
    tags:
      - 'v*' # Se ejecutará cuando crees una etiqueta de versión (ej: v0.4)

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Actualizando repositorio
      uses: actions/checkout@v4

    - name: Configurando Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Instalando dependencias
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt

    - name: Compilando con PyInstaller
      run: pyinstaller --onefile --name DungeonsGame main.py

    - name: Subiendo ejecutable a la Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/DungeonsGame.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
