name: Build Windows EXE

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Actualizando repositorio
      uses: actions/checkout@v4

    - name: Configurando Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Instalando dependencias
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install pyfiglet colorama 
        if (Test-Path requirements.txt) { pip install -r requirements.txt }

    - name: Compilando con PyInstaller
      run: pyinstaller --onefile --collect-all pyfiglet --clean --name DungeonsGame main.py

    - name: Subiendo ejecutable a la Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: dist/DungeonsGame.exe
        prerelease: true #Cambiar a false cuando acabe la beta
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}