name: Build Windows EXE

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Actualizando repositorio
      uses: actions/checkout@v4

    - name: Configurando Python
      uses: actions/setup-python@v5 # Actualizado a v5 para mejor estabilidad
      with:
        python-version: '3.12'

    - name: Instalando dependencias
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        # Es fundamental que pyfiglet y colorama estén en tu requirements.txt
        # O instalarlos directamente aquí:
        pip install pyfiglet colorama 
        if (Test-Path requirements.txt) { pip install -r requirements.txt }

    - name: Compilando con PyInstaller
      # --collect-all pyfiglet: Empaqueta las fuentes (.flf) dentro del EXE
      # --name DungeonsGame: Define el nombre del archivo final
      # --onefile: Mete todo (Python + librerías) en un único ejecutable
      run: pyinstaller --onefile --collect-all pyfiglet --clean --name DungeonsGame main.py

    - name: Subiendo ejecutable a la Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: dist/DungeonsGame.exe
        prerelease: true # Cambiado a false para versiones definitivas
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}